version: '3.8'
services:
  supabase:
    image: supabase/postgres:latest
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data
volumes:
  supabase_data:
